import { clsx, type ClassValue } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

/**
 * tailwind-merge must know our custom scales, otherwise it confuses
 * `text-body` (font-size) with `text-fg-muted` (color) and drops one.
 */
const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      text: [
        "display-2xl",
        "display-xl",
        "display-lg",
        "heading-lg",
        "heading-md",
        "heading-sm",
        "title",
        "body-lg",
        "body",
        "body-strong",
        "code",
        "label",
        "caption",
        "caption-strong",
        "overline",
        "micro",
        "figure-xl",
        "figure-lg",
      ],
      radius: ["xs", "sm", "md", "lg", "xl", "2xl", "pill"],
      shadow: ["flat", "xs", "card", "card-hover", "drag", "popover", "modal"],
      spacing: [
        "control-xs",
        "control-sm",
        "control-md",
        "control-lg",
        "control-xl",
        "icon-sm",
        "icon-md",
        "icon-base",
        "icon-lg",
        "row-sm",
        "row-md",
        "row-lg",
        "row-xl",
      ],
      color: [
        "fg-placeholder",
        "fg-on-accent-muted",
        "edge",
        "edge-strong",
        "focus-ring",
        "highlight",
        "disabled",
        "disabled-fg",
        "tile-on-color",
        "tile-on-color-hover",
        "edge-on-color",
        "scrim",
        "canvas",
        "surface",
        "surface-sunken",
        "surface-raised",
        "surface-hover",
        "surface-contrast",
        "surface-inverse",
        "skeleton",
        "fg-inverse",
        "fg-on-danger",
        "fg-on-success",
        "fg-on-warning",
        "fg-on-info",
        "disabled-border",
        "accent-pressed",
        "selected",
        "selected-ring",
        "rating",
        "chart-1",
        "chart-2",
        "chart-3",
        "chart-4",
        "chart-5",
        "chart-6",
        "chart-other",
        "chart-ord-1",
        "chart-ord-2",
        "chart-ord-3",
        "chart-ord-4",
        "chart-ord-5",
        "chart-seq-1",
        "chart-seq-2",
        "chart-seq-3",
        "chart-seq-4",
        "chart-seq-5",
        "chart-seq-6",
        "chart-seq-7",
        "chart-div-neg",
        "chart-div-mid",
        "chart-div-pos",
        "chart-grid",
        "chart-axis",
        "fg",
        "fg-muted",
        "fg-subtle",
        "fg-on-accent",
        "fg-on-contrast",
        "fg-on-contrast-muted",
        "border-subtle",
        "border",
        "border-strong",
        "accent",
        "accent-fg",
        "accent-hover",
        "accent-soft",
        "accent-soft-hover",
        "accent-soft-fg",
        "success",
        "success-soft",
        "success-fg",
        "warning",
        "warning-soft",
        "warning-fg",
        "danger",
        "danger-soft",
        "danger-fg",
        "info",
        "info-soft",
        "info-fg",
        "overlay",
        "white",
        "black",
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
