// Generates design-system/index.ts: the library entry that exposes every component under
// components/ (except the docs site) plus the stores, helpers and sample data a design needs.
// Run from the repo root: node design-system/scripts/gen-entry.mjs
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const COMPONENTS = join(ROOT, "components");
const OUT = join(ROOT, "design-system", "index.ts");

// Internal-only exports that must not reach the design agent.
const EXCLUDE = new Set(["InlineScript"]);
// Name collisions across folders: the second file's export gets an alias.
const RENAME = {
  "admin/admin-parts.tsx": { FilterBar: "AdminFilterBar" },
  "admin/orders/payment-status.tsx": { PaymentStatus: "AdminPaymentStatus" },
};

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const files = walk(COMPONENTS)
  .map((p) => relative(COMPONENTS, p).split("\\").join("/"))
  .filter((p) => p.endsWith(".tsx") && !p.startsWith("docs/"))
  .sort();

const exportRx = /^export (?:default )?(?:async )?(?:function|const|class) ([A-Z][A-Za-z0-9]*)/gm;
const seen = new Map();
const lines = [];
for (const f of files) {
  const src = readFileSync(join(COMPONENTS, f), "utf8");
  const names = [...src.matchAll(exportRx)].map((m) => m[1]).filter((n) => !EXCLUDE.has(n));
  if (!names.length) continue;
  const specs = names.map((n) => {
    const alias = RENAME[f]?.[n];
    const out = alias ?? n;
    if (seen.has(out)) throw new Error(`duplicate export ${out} in ${f} and ${seen.get(out)} - add a RENAME entry`);
    seen.set(out, f);
    return alias ? `${n} as ${alias}` : n;
  });
  lines.push(`export { ${specs.join(", ")} } from "../components/${f.replace(/\.tsx$/, "")}";`);
}

const header = `// GENERATED by design-system/scripts/gen-entry.mjs - do not edit by hand.
// BlueSigns component library entry: every component in components/ (docs excluded),
// plus stores, helpers and demo data for building designs.
`;

const extras = `
// Stores (toasts, bag, wishlist, theme...) and helpers
export * from "../components/providers/toast-store";
export * from "../components/providers/bag-store";
export * from "../components/providers/cart-store";
export * from "../components/providers/wishlist-store";
export * from "../components/providers/compare-store";
export * from "../components/providers/theme-store";
export * from "../components/providers/notifications-store";
export * from "../components/providers/recently-viewed-store";
export * from "../components/providers/search-store";
export * from "../components/providers/location-store";
export { cn } from "../lib/cn";
export * from "../lib/format";
export { computeBagTotals } from "../lib/pricing";

// Realistic demo data (products, orders, addresses, admin metrics...)
export * as sampleData from "./sample-data";

// The icon set the components use (lucide), e.g. icons.ShoppingBag
export * as icons from "lucide-react";
`;

writeFileSync(OUT, header + lines.join("\n") + "\n" + extras);
console.log(`wrote ${relative(ROOT, OUT)}: ${seen.size} components from ${lines.length} files`);
